name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Install dependences
        run: yarn

      - name: Build
        run: yarn build
